config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

    root 'quotes#home'

    get 'quotes/new' => 'quotes#new'
    get 'quotes/:id' => 'quotes#edit'
    resources :quotes
    get 'colours/new' => 'colours#new'
    get 'colours/:id' => 'colours#edit'
    resources :colours

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/colour.rb
class Colour < ActiveRecord::Base
    has_many :quotes
    belongs_to :user

def white_on_black?
    return self.white_on_black
end

def self.with_access( user )
    return user.colours.concat( self.public ).flatten
end

def self.public
    return Colour.where( public: true )
end

end

app/models/quote.rb
class Quote < ActiveRecord::Base
    belongs_to :colour
    belongs_to :user
    has_attached_file :audio
    validates_attachment :audio, content_type: { content_type: [ "audio/m4a", "audio/mpeg" ] }
    has_attached_file :background, styles: { thumb:"100x100#" }
    validates_attachment :background , content_type: { content_type: [ "image/png", "image/jpeg", "image/jpeg" ] }

#post: return an random quote, taking favorites into consideration
def self.random_quote
    return Quote.public.shuffle.first
end

#pre: current_user
#post: return an random quote, taking favorites into consideration
def self.random_quote_of_user( user )
    quotes = user.quotes.concat( Quote.favorites( user ) ).flatten #add duplicates to have higher chance to get picked
    quotes = Quote.public if quotes.blank?

return quotes.shuffle.first
end


#pre: current_user
#post: return all quotes that were favorited
def self.favorites( user )
    return user.quotes.where( favorite: true )
end

def self.public
    return Quote.where( public: true )
end

#post: exists c in Colours : quote.c = c
def colour?
    return !self.colour.blank?
end

#Always return a colour. If there is no associated colour, return a white colour
alias_method :original_colour, :colour
def colour
    return self.original_colour || Colour.new( name: "White", hex_value: "#FFF" )
end

end

app/models/user.rb
class User < ActiveRecord::Base
    authenticates_with_sorcery!

    validates :password, length: { minimum: 3 }
    validates :password, confirmation: true
    validates :password_confirmation, presence: true

    validates :email, uniqueness: true

    has_many :quotes
    has_many :colours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
    before_action :set_colours, only: [ :edit, :update, :destroy]

def index
    @colours = current_user.colours
    @public_colours = Colour.public
end

def new
    @colour = Colour.new
end

def edit #handeld by before action
end

def create
    @colour = Colour.new( colour_params )
    @colour.user = current_user

    respond_to do |format|
        if @colour.save
            format.html { redirect_to @colour, notice: 'Colour was successfully created.' }
            else
            format.html { render :new }
        end
    end
end

def update
    respond_to do |format|
        if @colour.update( colour_params )
            format.html { redirect_to @colour, notice: 'Colour was successfully updated.' }
            else
            format.html { render :edit }
        end
    end
end

def destroy
    @colour.destroy
    respond_to do |format|
        format.html { redirect_to colours_url, notice: 'Colour was successfully destroyed.' }
        format.json { head :no_content }
    end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_colours
    @colour = Colour.find( params[ :id ] )
end

# Never trust parameters from the scary internet, only allow the white list through.
def colour_params
    params.require( :colour ).permit( :name, :hex_value, :white_on_black, :public )
end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :set_quote, only: [ :edit, :update, :destroy ]
    skip_before_filter :require_login, only: [ :home ]

def index
    @quotes = current_user.quotes
    @public_quotes = Quote.public
end

def home
    @quote = ( current_user.blank? ? Quote.random_quote : Quote.random_quote_of_user( current_user ) )
end

def new
    @quote = Quote.new
end

def edit #handeld by before action
end

def create
    @quote = Quote.new(quote_params)
    @quote.user = current_user

    respond_to do |format|
        if @quote.save
            format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
            format.json { render :show, status: :created, location: @quote }
            else
            format.html { render :new }
            format.json { render json: @quote.errors, status: :unprocessable_entity }
        end
    end
end

def update
    respond_to do |format|
        if @quote.update(quote_params)
            format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
            format.json { render :show, status: :ok, location: @quote }
            else
            format.html { render :edit }
            format.json { render json: @quote.errors, status: :unprocessable_entity }
        end
    end
end

def destroy
    @quote.destroy
    respond_to do |format|
        format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
        format.json { head :no_content }
    end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_quote
    @quote = Quote.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def quote_params
    params.require( :quote ).permit( :quote, :author, :favorite, :colour_id, :audio, :background)
end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_filter :require_login, except: [:destroy]

def new
    @user = User.new
end

def create
    if @user = login( params[ :email ], params[ :password ],  params[ :remember ] )
        redirect_back_or_to( :users, notice: 'Login successful' )
    else
        flash.now[ :alert ] = 'Login failed'
        render action: 'new'
    end
end

def destroy
    logout
    redirect_to( root_path, notice: 'Logged out!' )
end

private
def not_authenticated
    redirect_to login_path, alert: "Please login first"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colours/_form.html.erb
<%= content_for :title, ( @colour.new_record? ? "Create a new colour" : @colour[ :name ] ) %>

<%= form_for( @colour, :html => { :class => 'form-horizontal' } ) do |f| %>
<% if @colour.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@colour.errors.count, "error") %> prohibited this colour from being saved:</h2>
    <ul>
        <% @colour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<fieldset>
    <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls"><%= f.text_field :name %></div>
        </div>
    <div class="control-group">
        <%= f.label :hex_value, class: 'control-label' %></span>
        <div class="controls"><%= f.text_field :hex_value %></div>
    </div>
    <div class="control-group">
        <%= f.label :white_on_black, class: 'control-label' %></span>
        <div class="controls"><%= f.check_box :white_on_black %></div>
    </div>
    <div class="control-group">
        <%= f.label :public, class: 'control-label' %></span>
        <div class="controls"><%= f.check_box :public %></div>
    </div>
    <div class="control-group">
        <div class="controls">
        <%= f.submit class: 'btn'  %>
        </div>
    </div>
</fieldset>
<% end %>

app/views/colours/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @colour %> |
<%= link_to 'Back', colours_path %>

app/views/colours/index.html.erb
<%= content_for :title, "Colours" %>
<%= content_for :background_colour, "#FFF" %>

<h2>Your colours</h2>
<ul>
    <% @colours.each do |colour| %>
        <li>
            <%= link_to colour[ :name ], edit_colour_path( colour ) %> | <%= link_to 'Destroy', colour, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </tr>
    <% end %>
</ul>

<h2>Public colours</h2>
<ul>
    <% @public_colours.each do |colour| %>
        <li>
            <%= link_to colour[ :name ], edit_colour_path( colour ) %> | <%= link_to 'Destroy', colour, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </tr>
    <% end %>
</ul>

<%= link_to 'New Colour', new_colour_path %>

app/views/colours/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', colours_path %>

app/views/layouts/_background.html.erb
<style>
body{
    background-color: <%= yield :background_colour %>;
    background-image: url( <%= yield :background_image %> );
}
</style>

app/views/layouts/_header.html.erb
​​<% if notice %>
    <p class="notification notice">
        <%= notice %>
    </p>
<% end %>
<% if alert %>
    <p class="notification alert">
        <%= alert %>
    </p>
<% end %>

<div id='hdrCenter' class='column'>
    <%= yield :title %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Quotes', quotes_path %></li>
            <li><%= link_to 'Colours', colours_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li><%= link_to "Logout", :logout, method: :post %></li>
            <% else %>
                <li><%= link_to "Register", new_user_path %></li>
                <li><%= link_to "Login", :login %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Fukurokuju</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/background' %>
    </head>
    <body>
        <header>
            <%= render 'layouts/navigation' %>
            <%= render 'layouts/header' %>
        </header>
        <div class="container" role="main">
        <%= yield %>
        </div>
    </body>
</html>

app/views/quotes/_form.html.erb
<%= content_for :title, ( @quote.new_record? ? "Create a new quote" : "Quote by " + @quote[ :author ] ) %>

<%= form_for( @quote, html: { class: 'form-horizontal', multipart: true } ) do |f| %>
<% if @quote.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
    <ul>
        <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<fieldset>
    <div class="control-group">
        <%= f.label :quote, class: 'control-label' %>
        <div class="controls"><%= f.text_area :quote, size: '60x5' %></div>
        </div>
    <div class="control-group">
        <%= f.label :author, class: 'control-label' %></span>
        <div class="controls"><%= f.text_field :author %></div>
    </div>
    <div class="control-group">
        <%= f.label :favorite, class: 'control-label' %></span>
        <div class="controls"><%= f.check_box :favorite %></div>
    </div>
    <% unless @quote.colour.blank? %>
    Current colour: <%= @quote.colour.name %>
    <% end %>
        <% current_user.colours.each do |colour| %>
            <div class="control-group">
                <%= f.radio_button( :colour_id, colour[ :id ] ) %>
                <%= label_tag( :colour_id, colour[ :name ], class: 'control-label' ) %>
            </div>
        <% end %>
        <label class='control-label'>Public Colours</label>
        <% Colour.public.each do |colour| %>
        <% unless colour.blank? %>
        <div class="control-group">
            <%= f.radio_button( :colour_id, colour[ :id ] ) %>
            <%= label_tag( :colour_id, colour[ :name ], class: 'control-label' ) %>
        </div>
        <% end %>
        <% end %>
        <div class="control-group">
            Currently has audio file: <%= ( @quote.audio.exists? ?  @quote.audio.original_filename : "None") %>h
            <%= f.file_field :audio %>
        </div>
        <div class="control-group">
            Currently has background: <%= ( @quote.background.exists? ? image_tag( @quote.background.url(:thumb) ) : "None" ) %>
            <%= f.file_field :background %>
        </div>
        <div class="control-group">
            <%= f.label :public, class: 'control-label' %></span>
            <div class="controls"><%= f.check_box :public %></div>
        </div>

    <div class="control-group">
        <div class="controls">
        <%= f.submit class: 'btn'  %>
        </div>
    </div>
</fieldset>
<% end %>

app/views/quotes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/home.html.erb
<%= content_for :background_colour, @quote.colour.hex_value %>
<%= content_for :background_image, ( @quote.background.exists? ? @quote.background.url : "none" ) %>

<% if @quote.audio.exists? %>
<%= audio_tag @quote.audio.url, autoplay: true, loop: true %>
<% end %>

<article id=<%= "quote_"+ @quote.id.to_s %> class='quote'>
<blockquote class=<%= "white_on_black" if @quote.colour.white_on_black? %>>
    <p><%= @quote.quote %></p>
    <cite><%= @quote.author %></cite>
</blockquote>

</article>

app/views/quotes/index.html.erb
<%= content_for :title, "Quotes" %>
<%= content_for :background_colour, "#FFF" %>

<h2>Your quotes</h2>
<ul>
    <% @quotes.each do |quote| %>
        <li>
            <%= link_to quote[:quote], edit_quote_path(quote) %>, by <%= quote[ :author ] %> | <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </tr>
    <% end %>
</ul>

<h2>Public quotes</h2>
<ul>
    <% @public_quotes.each do |quote| %>
        <li>
            <%= link_to quote[:quote], edit_quote_path(quote) %>, by <%= quote[ :author ] %> | <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </tr>
    <% end %>
</ul>


<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
<div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
</div>
<div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
</div>

<div class="field">
    <%= label_tag :remember %><br />
    <%= check_box_tag :remember %>
</div>

<div class="actions">
    <%= submit_tag "Login", class: 'btn' %>
</div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<% content_for :title, 'Login' %>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
        <%= f.submit class: 'btn' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>